# Generated by Django 3.2.7 on 2023-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='Message',
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='chat_media/'),
        ),
    ]
